"""add session message diagnosis medication visitlog

Revision ID: 7c0adb8d2e93
Revises: 3307fbcba0b6
Create Date: 2026-08-01 17:51:14.119608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c0adb8d2e93'
down_revision: Union[str, Sequence[str], None] = '3307fbcba0b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
